name: Update GitHub Snake

# Give the GITHUB_TOKEN write access to repo contents
permissions:
  contents: write

on:
  schedule:
    # every day at 00:00 UTC
    - cron: '0 0 * * *'
  push:
    branches: [ main, master ]

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # persist-credentials is true by default, so this checkout
        # will use the write-enabled token we granted above.

      - name: Generate light & dark SVG-only Snakes
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # light-mode snake in purple (RGB 128,0,128)
            output/github-snake-light.svg?palette=github-light&color_snake=128,0,128
            # dark-mode snake (uses GitHub’s dark palette)
            output/github-snake-dark.svg?palette=github-dark&color_snake=128,0,128

      - name: Commit updated snakes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-snake-light.svg output/github-snake-dark.svg
          git commit -m "chore: update github-snake svgs" || echo "No changes to commit"
          git push

